version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - database
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'your_database_name'
      MYSQL_USER: 'your_database_user'
      MYSQL_PASSWORD: 'your_database_password'
      MYSQL_ROOT_PASSWORD: 'your_root_password'
    ports:
      - "3306:3306"


